# Generated by Django 5.2.3 on 2025-07-07 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_follow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='created_at',
        ),
    ]
