# Generated by Django 5.2.3 on 2025-07-11 23:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_follow_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='audio_file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='audio_file'),
        ),
        migrations.AlterField(
            model_name='track',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover_image'),
        ),
    ]
